name: Build Flutter APK and IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3.3.0

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.15.0
      with:
        flutter-version: '3.13.0'

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Build IPA
      run: |
        cd ios
        pod install
        cd ..
        flutter build ios --no-codesign

    - name: Upload APK and IPA
      uses: actions/upload-artifact@v4.0.0
      with:
        name: Build Outputs
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/ios/iphoneos/Runner.app

